export const phaseData = {
  "Menstrual Phase": {
    Food: [
      "Iron Rich Foods",
      "- Especially focuses on maintaining the iron lost due to bleeding and prevents anemia.",
      "  1. Spinach                  2. Lentils",
      "  3. Beets                    4. Egg yolks",
      "  5. Liver                    6. Gundruk",
      "  7. Black chana              8. Niuro",
      "  9. Mutton                  10. Bhatmas",
      "  * Pair foods with tomatoes or oranges for better iron absorption.",

      "Warm Foods",
      "- Boost low energy and reduce cravings.",
      "  1. Khichadi (Mung dal + rice)        2. Chicken or Bone soups",
      "  3. Ginger tea                        4. Turmeric milk",
      "  5. Milk + rice                       6. Vegetable soup",
      "  * Food cooked in small amounts of ghee.",

      "Anti-Inflammatory Foods",
      "- Reduces cramps and bloating.",
      "  1. Ginger                            2. Turmeric",
      "  3. Cumin (Jeera)                    4. Fish",
      "  5. Berries (Strawberries or Blueberries)",

      "Hydrating Foods",
      "- Maintain water and blood volume.",
      "- Dehydration worsens cramps and fatigue.",
      "  1. Cucumber                          2. Lemon water",
      "  3. Watermelon                        4. Oranges",
      "  5. Coconut water                     6. Soups",
      "  7. Fruits (High in water + fiber)",

      "Mood Boosting Foods",
      "- Support good moods.",
      "  1. Banana                            2. Dark chocolate",
      "  3. Milk + turmeric                   4. Nuts (almonds, walnuts)",
      "  5. Pumpkin seeds",

      "Tips",
      "- Avoid salty, processed, fried foods.",
      "- Cut down on caffeine.",
      "- Reduce sugary sweets; opt for warm water or herbal teas.",
      "- Avoid cold drinks and ice creams—they worsen cramps.",
    ],
    Exercise: [
      "Yoga Poses",
      "- Balasana: Relieves lower back pain, calms mind",
      "- Cat-Cow Stretch (Marjaryasana Bitilasana): Stretches spine gently and improves flow",
      "- Viparita Karani: Reduces fatigue, improves circulation",
      "- Supta Baddha Konasana: Reduces cramps",
      "- Apanasana (Knee to Chest Pose): Aids digestion, eases bloating",

      "Meditation & Breathing",
      "- Anulom Vilom: Balances hormones, calms mood",
      "- Deep Belly Breathing: Calms nervous system, relieves cramps",
      "- Womb Meditation: Promotes physical, emotional, and spiritual healing",

      "Resting",
      "- Use warm water bottle on abdomen or back",
      "- Listen to calming music, mantras, or guided meditations",
      "- For relaxation, practice Shavasana",

      "Light Exercises",
      "- Slow walking",
      "- Gentle stretching",
      "- Massage",
    ],
    Focus: [
      "Living",
      "- This is your natural “winter”. Sleep more, take short naps, reduce social obligations.",
      "- Don’t overthink anything that’s not working for you — let it go.",
      "- Make fewer decisions and enjoy personal time.",
      "- Create a calm vibe: use quiet spaces, soft lighting, and slow music.",
      "- Restore self-confidence. Do tasks that make you feel joy and comfort.",

      "Working",
      "- Do tasks that require less collaboration and more deep thinking.",
      "- Good time for writing, journaling, and visioning future ideas.",
      "- Communicate if you need quiet time or personal space.",
      "- Reflect on past work and refine your plans.",
      "- Take care of your body; it's okay to say no to invitations.",
    ],
    Love: [
      "Relationships",
      "- In this phase, you're more sensitive and emotionally raw.",
      "- You might not feel like texting or going out — let friends/partner know you're recharging.",
      "- If in a romantic relationship, small gestures like a hug or cup of tea can be deeply nourishing.",
      "- You may feel more emotionally intense — give yourself space before reacting.",
      "- Reflect on whether your relationships make you feel strong and supported.",

      "Sex Status",
      "- It's your time — if you don’t feel like engaging in sex (solo or with a partner), take a break.",
      "- Low sex drive is normal due to cramps or fatigue.",
      "- To stay close without intercourse, try cuddling, massage, or holding hands in a warm space.",
    ],
  },
  "Follicular Phase": {
    Food: [
      "Brain-Boosting & Energy Foods",
      "- Supports brain focus and stable blood sugar.",
      "  1. Eggs                            2. Avocado",
      "  3. Oats + nuts                    4. Grains (millet, brown rice, barley)",
      "  5. Banana                         6. Spinach",
      "  7. Pumpkin seeds                 8. Peanut Butter",

      "Hormone Supporting Foods",
      "- Helps rising estrogen level naturally and balances rising energy.",
      "  1. Chana                          2. Sprouted lentils (soaked dal)",
      "  3. Moong dal                      4. Gundruk",
      "  5. Yogurt (Dahi)                  6. Cauliflower, Cabbage, Broccoli",
      "  7. Fish                            8. Apples, Papaya",
      "  9. Berries (Strawberry)",

      "Hydrating Foods",
      "- Body feels fresher and more energetic.",
      "  1. Lemon + honey water            2. Cucumber",
      "  3. Mint                           4. Coconut water",
      "  5. Citrus fruits                  6. Fruits (Apples, Oranges, Pears)",

      "Tips",
      "- Continue warm teas with herbs like ginger, tulsi, mint.",
      "- Avoid oily and fried foods.",
      "- Have fruits daily or frequently.",
    ],
    Exercise: [
      "Yoga Poses",
      "- Surya Namaskar",
      "  * Best on empty stomach.",
      "  * Sharpens mind and warms up all muscles.",
      "  * Breathe deeply and slowly.",
      "- Virabhadrasana I & II",
      "  * Improves posture and focus.",
      "  * Hold for 20–30 sec per side, 2–3 times.",
      "- Ustrasana",
      "  * Increases energy and improves posture.",
      "  * Stretches hips, belly, and chest.",
      "  * Hold for 15–30 sec, repeat 2–3 times.",
      "- Setu Bandhasana",
      "  * Strengthens back, hips, and thighs.",
      "  * Opens hips and heart area.",
      "  * Hold for 30 sec to 1 min, repeat 2–3 times.",
      "  * Tip: Do not stretch too hard; warm up first.",

      "Meditation & Breathing",
      "- Kapalbhati",
      "  * Boosts metabolism and clears toxins.",
      "  * Do in the morning on empty stomach.",
      "  * Take a deep breath and forcefully exhale through nose for 5 min.",
      "  * Precaution: Avoid during menstruation, BP, or hernia.",
      "- Bhramari",
      "  * Calms the nervous system and improves sleep.",
      "  * Inhale deeply, exhale with a humming sound (mmmm).",
      "  * Close ears with thumbs for deeper effect.",
      "  * Do 20–30 sec, 5–7 rounds.",
      "- Visualization Meditation",
      "  * Builds self-confidence, boosts creativity and focus.",
      "  * Sit comfortably in a peaceful space.",
      "  * Close eyes, take deep breaths.",
      "  * Visualize happiness and things you love.",
      "  * Practice for 5–10 minutes daily.",
    ],
    Focus: [
      "Living",
      "- Your energy starts to rise—it's time to rejoin life with creativity and motivation.",
      "- Try something new: a hobby, skill, or event.",
      "- Best time to plan dreams and create strategies.",
      "- Explore new things, say yes to new opportunities.",
      "- Your brain craves freshness—do cleaning or reset your space.",

      "Working",
      "- You’re mentally alert and energetic—perfect for work and creative thinking.",
      "- Continue deep work with boosted energy.",
      "- Communication is strong—engage in teamwork.",
      "- Great time for interviews, meetings, workshops.",
      "- Start new projects, pitch ideas, experiment freely.",
    ],
    Love: [
      "Relationships",
      "- At this phase, you are more playful , laughing , meeting new people and being more social.",
      "- Reconnect with friends, go on dates, plan group events.",
      "- This is the great time to resolve the issues as you are mentally calm and emotionally balanced.",
      "- As your self confidence rises , letting people love you recharge you emotionally.",
      "- If single, it’s a great time to meet new people or go on dates.",

      "Sex Status",
      "- Your sex drive is increasing during this phase.",
      "- your skin glows , energy returns and feel more attractive and you want to feel bolder.",
      "- Try new things in relationship , communicate with your partner.",
      "- Express yourself . Go for walk , teasing , cuddling deepens closeness with your partner.",
    ],
  },
  "Ovulatory Phase": {
    Food: [
      "Cooling & Anti-Inflammatory Foods",
      "  1. Cucumber                      2. Watermelon",
      "  3. Yogurt / Curd                4. Lemon water",
      "  5. Mint (Pudina)                6. Citrus fruit (Oranges)",
      "  7. Amala juice                  8. Fenugreek water (Methi pani)",

      "Fertility Boosting Foods",
      "  1. Eggs                         2. Pumpkin seeds",
      "  3. Pomegranate                  4. Cauliflower / Cabbage",
      "  5. Green leafy vegetables       6. Avocado",
      "  7. Chicken                      8. Gundruk",
      "  9. Mushrooms                   10. Dal (Mung dal / Musuro dal)",

      "Higher Fiber Foods",
      "  1. Apple                        2. Pear (Nashpati)",
      "  3. Lentils (Rahar / Musuro dal) 4. Millet",
      "  5. Barley / Brown rice          6. Corn flour",

      "Tips",
      "- Stay hydrated with herbal teas (tulsi + ginger), lemon or mint water.",
      "- Avoid deep-fried and spicy foods.",
      "- Include foods like gundruk and yogurt.",
      "- Avoid sugary drinks and excess tea/coffee.",
    ],
    Exercise: [
      "Yoga Poses",
      "- Bhujangasana",
      "  * Boosts energy and mood.",
      "  * Opens the heart and improves spinal flexibility.",
      "  * Inhale and lift chest gently, hold for 20–30 seconds.",
      "  * Repeat 3–4 times.",
      "- Dhanurasana (Bow Pose)",
      "  * Stimulates ovaries and uterus, relieves back pain.",
      "  * Inhale deeply, lift chest and legs, hold 15–30 sec.",
      "  * Repeat 2–3 times.",
      "- Utkatasana",
      "  * Strengthens thighs, hips, spine, and boosts stamina.",
      "  * Hold 30–40 seconds, repeat 3 times.",
      "- Plank Pose",
      "  * Strengthens arms, shoulders, and legs.",
      "  * Improves posture and endurance.",
      "  * Hold for 30–60 seconds, repeat twice.",

      "Meditation & Breathing",
      "- Bhramari",
      "  * Calms nervous system, reduces stress.",
      "  * Hum gently while exhaling, with ears closed for effect.",
      "  * 20–30 seconds, 5–7 rounds.",
      "- Chandra Bhedana",
      "  * Balances hormonal energy and cools the body.",
      "  * Inhale through left nostril, exhale through right.",
      "  * Repeat for 3–5 minutes.",

      "Other Exercises",
      "- Running, swimming, cycling (20–40 mins).",
      "- Intense activities: jumping, squats, climbing.",
      "- Group classes like dance or Zumba.",
    ],
    Focus: [
      "Living",
      "- This is the time when you are glowing, sociable and very confident.",
      "- Go out, host events, meet new people.",
      "- Try new things: dancing , hosting , speaking and expanding network.",
      "- Dress up in ways where you boost your self image.",
      "- Your skin glows up and posture improve.",

      "Working",
      "- You are at your peak mental sharpness and social fluency.",
      "- Ideal time for leadership, public speaking, and collaboration.",
      "- Great time for critical work and showing you real ability.",
      "- Best phase for brainstorming ideas and initiating projects.",
      "- In this phase your brain wants interaction rather than silent focus.",
      "- This is your superwoman work phase",
      "Tips: Avoid solo deep work like heavy research now.",
    ],
    Love: [
      "Relationships",
      "- In this phase , hormones increase confidence, affection and emotional openness.",
      "- Go out talk to people , organize gatherings.",
      "- Its great time to resolve past issues calmly with partner , friends, family.",
      "- In this phase you are more open and flirty so you can express feelings or take the lead in romance.",
      "- Perfect time for dating, meetups and explore new social circles.",

      "Sex Status",
      "- Hormones works together in this phase increasing the sex drive.",
      "- You can plan a romantic evening or weekend.",
      "- Show slow and emotional affection towards the partner.",
      "- Its great time to have open communication like sharing your preferences with your partner.",
      "- This is the phase to explore the pleasure for yourself.",
    ],
  },
  "Luteal Phase": {
    Food: [
      "Warming & Comforting Foods",
      "- Relax the nervous system, improve digestion and make you calm.",
      "  1. Warm Soups (Dal soup, Bone soup)     2. Sweet Potato",
      "  3. Turmeric milk                       4. Banana",
      "  5. Ginger tea                          6. Brown rice",
      "  7. Vegetables with ghee (carrots, beans)  8. Cumin water (Jeera pani)",

      "Hormone Supporting Foods",
      "- Help produce progesterone, balance mood swings and energy.",
      "  1. Eggs                                2. Fatty Fish",
      "  3. Chicken                             4. Avocado",
      "  5. Sesame seeds (Til)                 6. Paneer",
      "  7. Millet (Kodo)                      8. Barley (Jau)",
      "  9. Almonds and Walnuts",

      "Cramp & Bloating Relief Foods",
      "- Helps to reduce cramps, bloating and indigestion.",
      "  1. Papaya                              2. Yogurt",
      "  3. Cucumber                            4. Pineapple",
      "  5. Beetroot (Chukandar)               6. Warm lemon water",
      "  7. Coriander seed water (Dhaniya pani) 8. Spinach / Green leafy vegetables",

      "Tips",
      "- Reduce excess salt and sugar.",
      "- Limit caffeine and alcohol.",
      "- Stay hydrated.",
      "- Avoid cold foods and drinks.",
    ],
    Exercise: [
      "Yoga Poses",
      "- Apanasana",
      "  * Relieves lower back pain, gas and bloating.",
      "  * Take deep breaths and hold for 2–3 minutes.",
      "- Ananda Balasana (Happy Baby)",
      "  * Reduces cramps and opens hips.",
      "  * Calms mood, breathe slowly for 2–3 minutes.",
      "- Parivrtta Janu Sirsasana",
      "  * Supports digestion and stretches body gently.",
      "  * Hold 30 sec each side, 2 times.",
      "  * Avoid if tired or cramping.",
      "- Supta Matsyendrasana",
      "  * Relieves tension in abdomen and spine.",
      "  * Hold for 1–2 minutes on each side, repeat twice.",

      "Meditation & Breathing",
      "- Nadi Shodhana (Alternate Nostril Breathing)",
      "  * Calms anxiety, balances hormones, supports emotional stability.",
      "  * Inhale through left, exhale right — repeat 3–5 minutes.",
      "- Yoga Nidra",
      "  * Deep rest, reduces PMS and emotional imbalance.",
      "  * Lie down, imagine what you love, do for 10–20 mins.",
      "- Bhramari",
      "  * Gentle humming sound relaxes nervous system.",
      "  * 20–30 seconds per round, repeat 5–7 times.",

      "Tips",
      "- Avoid intense strength training.",
      "- Prefer walking (20–30 mins), dancing, or nature time.",
      "- Avoid competitive or high-stress workouts.",
    ],
    Focus: [
      "Living",
      "- You may feel more emotional and sensitive , that’s normal.",
      "- Don't force yourself to socialize.",
      "- Surround yourself with calming things: soft lighting , clean spaces , herbal teas etc.",
      "- If you need time alone let the close ones know.",
      "- Choose peace over pleasure.",
      "- Try to take break from social media before an hour before bed time.",

      "Working",
      "- Don’t go for highly stressing works .",
      "- Not ideal time for public speaking or networking.",
      "- Avoid roles that demands intense energy like leadership roles.",
      "- Go for quiet space and creative works.",
      "- You can have good productivity but slow pace.",
      "- Take more breaks than usual , if you feel emotionally more reactive.",

      "Tip",
      "- Don’t force yourself into high output.",
    ],
    Love: [
      "Relationships",
      "- You feel more easily hurt and emotional. Small issues might feel big, give yourself space",
      "- Don’t force yourself into conversations or social plans, its okay to say no",
      "- Try to stay away from arguments, cause in this phase arguments can lead worse",
      "- Its common to overthink in this phase, instead of overthinking do simple things like watch movie , spend time with someone calm",

      "Sex Status",
      "- You may not fell sexy cause your body wants comfort than pressure",
      "- Focus on cuddling, massage or lying close together",
      "- Go for slow and emotional intimacy, if you are in good mood",
      "- Don’t be afraid to say what you want clearly to your partner",
      "- If you are single, give time to yourself",

      "Tips:",
      "- Avoid unnecessary conflicts",
      "- Focus on self- love",
      "- Prioritize yourself before anything",
    ],
  },
};
