const bullet = "•";
export const phaseData = {
  "Menstrual Phase": {
    Food: [
      "Iron Rich Foods",
      "- Especially focuses on maintaining the iron lost due to bleeding and prevents anemia.",
      "  1. Spinach                  2. Lentils",
      "  3. Beets                    4. Egg yolks",
      "  5. Liver                    6. Gundruk",
      "  7. Black chana              8. Niuro",
      "  9. Mutton                  10. Bhatmas",
      "  * Pair foods with tomatoes or oranges for better iron absorption.",

      "Warm Foods",
      "- Boost low energy and reduce cravings.",
      "  1. Khichadi (Mung dal + rice)        2. Chicken or Bone soups",
      "  3. Ginger tea                        4. Turmeric milk",
      "  5. Milk + rice                       6. Vegetable soup",
      "  * Food cooked in small amounts of ghee.",

      "Anti-Inflammatory Foods",
      "- Reduces cramps and bloating.",
      "  1. Ginger                            2. Turmeric",
      "  3. Cumin (Jeera)                    4. Fish",
      "  5. Berries (Strawberries or Blueberries)",

      "Hydrating Foods",
      "- Maintain water and blood volume.",
      "- Dehydration worsens cramps and fatigue.",
      "  1. Cucumber                          2. Lemon water",
      "  3. Watermelon                        4. Oranges",
      "  5. Coconut water                     6. Soups",
      "  7. Fruits (High in water + fiber)",

      "Mood Boosting Foods",
      "- Support good moods.",
      "  1. Banana                            2. Dark chocolate",
      "  3. Milk + turmeric                   4. Nuts (almonds, walnuts)",
      "  5. Pumpkin seeds",

      "Tips",
      "- Avoid salty, processed, fried foods.",
      "- Cut down on caffeine.",
      "- Reduce sugary sweets; opt for warm water or herbal teas.",
      "- Avoid cold drinks and ice creams—they worsen cramps.",
    ],
    Exercise: [
      // ==================== YOGA POSES ====================
      { type: "header", text: "Yoga Poses" },

      {
        type: "exercise",
        category: "yoga",
        name: "Balasana",
        image: require("../../assets/images/periods-exercise/Balasana.png"),
        steps: [
          "1. Sit on your knees, feet together",
          "2. Bend forward slowly, chest between thighs",
          "3. Stretch hands forward or keep near feet",
          "4. Forehead on floor, breathe slowly",
          "5. Hold for 2-3 minutes",
        ],
        benefits: ["Relieves lower back pain, calms mind"],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Cat-Cow Stretch",
        image: require("../../assets/images/periods-exercise/cat-cow.png"),
        steps: [
          "1. Get on the pose",
          `${bullet}  Cow Pose`,
          "       Take a breath in, lift your head up, and let your \t\t\t\tbelly drop down",
          `${bullet}  Cat Pose`,
          "       Breathe out, round your back up like a scared \t\t\tcat, and look at your belly",
          "2. Do this slowly 5–10 times, breathing with each move.",
        ],
        benefits: ["Stretches spine gently and improves flow"],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Viparita Karani",
        image: require("../../assets/images/periods-exercise/vparita-karani.png"),
        steps: [
          "1. Sit near a wall.",
          "2. Lie down and lift your legs up, placing them straight on the wall.",
          "3. Let your hands rest by your side.",
          "4. Close your eyes and relax.",
          "5. Stay like this for 5–10 minutes.",
        ],
        benefits: ["Reduces fatigue, improves circulation"],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Supta Baddha Konasana",
        image: require("../../assets/images/periods-exercise/supta-buddha-konasana.png"),
        steps: [
          "1. Lie down on your back.",
          "2. Join your feet together, and let your knees fall open like butterfly wings.",
          "3. Put your hands on your belly or sides.",
          "4. Breathe gently and relax for 5–10 minutes.",
        ],
        benefits: ["Reduces cramps"],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Apanasana",
        image: require("../../assets/images/periods-exercise/apanasana.png"),
        steps: [
          "1. Lie down on your back.",
          "2. Bring one knee close to your chest and hold it with both hands.",
          "3. Breathe slowly for about 5 -10 breaths. Then switch legs.",
          "4. You can also bring both knees together to your chest.",
        ],
        benefits: ["Aids digestion, eases bloating"],
      },

      // ============= MEDITATION & BREATHING =============
      { type: "header", text: "Meditation & Breathing" },

      {
        type: "exercise",
        category: "meditation",
        name: "Anulom Vilom",
        // image: require("@assets/images/period-exercise/anulom_vilom.jpg"),
        steps: [
          "1. Sit comfortably with your back straight.",
          "2. Close your eyes and relax your face.",
          "3. Use your **right thumb** to **close** your right nostril.",
          "4. Breathe in slowly through your left nostril.",
          "5. Now close your left nostril with your ring finger.",
          "6. Open your right nostril and breathe out slowly.",
          "7. Now breathe in from the right nostril",
          "8. Close it, and breathe out from the left nostril.",
          "9. This is one full round.",
          "10. Repeat slowly for 10-15 rounds, focusing on your breath.",
        ],
        benefits: ["Balances hormones, calms mood"],
      },
      {
        type: "exercise",
        category: "meditation",
        name: "Deep Belly Breathing",
        image: require("../../assets/images/periods-exercise/deep-belly-breathing.png"),
        steps: [
          "1. Sit or lie down comfortably.",
          "2. Place one hand on your belly and one on your chest.",
          "3. Breathe in slowly through your nose.",
          "    – Feel your belly rise like a balloon.",
          "4. Breathe out slowly through your mouth.",
          "    – Feel your belly fall.",
          "5. Keep your shoulders relaxed.",
          "6. Do this slowly for 5–10 minutes.",
          "    – Focus only on the belly moving, not the chest.",
        ],
        benefits: ["Calms nervous system, relieves cramps"],
      },
      {
        type: "exercise",
        category: "meditation",
        name: "Womb Meditation",
        image: require("../../assets/images/periods-exercise/womb-meditation.png"),
        steps: [
          "1. Sit or lie down in a quiet place.",
          "2. Place both hands on your womb (below the belly button).",
          "3. Keep your hands there the whole time.",
          "4. Close your eyes and take a few deep breaths.",
          "5. Focus on the warmth of your hands on your womb.",
          "6. Imagine a soft, glowing light in that space.",
          "7. Silently say kind words, like:",
          "    “I am safe. I am healing. I am whole.”",
          "8  Stay in this feeling for 5–10 minutes or longer.",
          "9  End by slowly opening your eyes and taking a deep breath.",
        ],
        benefits: ["Promotes physical, emotional and spiritual healing"],
      },

      // ==================== RESTING ====================
      { type: "header", text: "Resting" },
      {
        type: "text",
        content: "- Use warm water bottle on abdomen or back",
      },
      {
        type: "text",
        content:
          "- Listen to calming music, mantra, or guided sleep meditations",
      },
      {
        type: "text",
        content: "- For relaxation, practice Shavasana",
      },

      // ============== LIGHT EXERCISES ==============
      { type: "header", text: "Light Exercises" },
      {
        type: "text",
        content: "- Slow walking",
      },
      {
        type: "text",
        content: "- Gentle stretching",
      },
      {
        type: "text",
        content: "- Massage",
      },
    ],
    Focus: [
      "Living",
      "- This is your natural “winter”. Sleep more, take short naps, reduce social obligations.",
      "- Don’t overthink anything that’s not working for you — let it go.",
      "- Make fewer decisions and enjoy personal time.",
      "- Create a calm vibe: use quiet spaces, soft lighting, and slow music.",
      "- Restore self-confidence. Do tasks that make you feel joy and comfort.",

      "Working",
      "- Do tasks that require less collaboration and more deep thinking.",
      "- Good time for writing, journaling, and visioning future ideas.",
      "- Communicate if you need quiet time or personal space.",
      "- Reflect on past work and refine your plans.",
      "- Take care of your body; it's okay to say no to invitations.",
    ],
    Love: [
      "Relationships",
      "- In this phase, you're more sensitive and emotionally raw.",
      "- You might not feel like texting or going out — let friends/partner know you're recharging.",
      "- If in a romantic relationship, small gestures like a hug or cup of tea can be deeply nourishing.",
      "- You may feel more emotionally intense — give yourself space before reacting.",
      "- Reflect on whether your relationships make you feel strong and supported.",

      "Sex Status",
      "- It's your time — if you don’t feel like engaging in sex (solo or with a partner), take a break.",
      "- Low sex drive is normal due to cramps or fatigue.",
      "- To stay close without intercourse, try cuddling, massage, or holding hands in a warm space.",
    ],
  },
  "Follicular Phase": {
    Food: [
      "Brain-Boosting & Energy Foods",
      "- Supports brain focus and stable blood sugar.",
      "  1. Eggs                            2. Avocado",
      "  3. Oats + nuts                    4. Grains (millet, brown rice, barley)",
      "  5. Banana                         6. Spinach",
      "  7. Pumpkin seeds                 8. Peanut Butter",

      "Hormone Supporting Foods",
      "- Helps rising estrogen level naturally and balances rising energy.",
      "  1. Chana                          2. Sprouted lentils (soaked dal)",
      "  3. Moong dal                      4. Gundruk",
      "  5. Yogurt (Dahi)                  6. Cauliflower, Cabbage, Broccoli",
      "  7. Fish                            8. Apples, Papaya",
      "  9. Berries (Strawberry)",

      "Hydrating Foods",
      "- Body feels fresher and more energetic.",
      "  1. Lemon + honey water            2. Cucumber",
      "  3. Mint                           4. Coconut water",
      "  5. Citrus fruits                  6. Fruits (Apples, Oranges, Pears)",

      "Tips",
      "- Continue warm teas with herbs like ginger, tulsi, mint.",
      "- Avoid oily and fried foods.",
      "- Have fruits daily or frequently.",
    ],
    Exercise: [
      // ==================== YOGA POSES ====================
      { type: "header", text: "Yoga Poses" },

      {
        type: "exercise",
        category: "yoga",
        name: "Surya Namaskar",
        // image: require("../../assets/images/periods-exercise/surya-namaskar.png"),
        steps: [
          "1. Best on empty stomach",
          "2. Sharpens mind and warm up all muscles",
          "3. Breathe deeply and slow",
        ],
        benefits: ["Sharpens mind and warms up all muscles"],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Virabhadrasana I",
        image: require("../../assets/images/periods-exercise/virabhadrasana.png"),
        steps: [
          "1. Step your left leg back, bend the right knee",
          "2. Raise both arms straight up, face forward",
          "3. Hold for 20–30 seconds",
          "4. Come back to standing and switch legs",
          "5. Repeat the same steps on the other side",
          "6. Repeat 2-3 times per leg",
        ],
        benefits: ["Improves posture and focus", "Builds posture and focus"],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Ustrasana",
        // image: require("../../assets/images/periods-exercise/ustrasana.png"),
        steps: [
          "1. Kneel down, knees hip-width apart",
          "2. Place hands on lower back",
          "3. Slowly lean back and look up",
          "4. If comfortable, hold your heels",
          "5. Hold for 15–30 seconds and come up gently",
          "6. Repeat 2 to 3 times",
        ],
        benefits: [
          "Increase energy and improves posture.",
          "Stretches hips, belly and chest",
        ],
        tips: "Do not stretch too hard and do this after some warmups",
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Setu Bandhasana",
        image: require("../../assets/images/periods-exercise/setu-bandhasana.png"),
        steps: [
          "1. Lie on your back, bend your knees",
          "2. Place feet flat on the floor, arms by your side",
          "3. Press feet down and lift your hips up",
          "4. Hold for 30 sec–1 min, then slowly come down",
          "5. Breathe slowly",
          "6. Repeat for 2-3 times",
        ],
        benefits: [
          "Strengthens back, hips and thighs.",
          "Opens hips and heart area",
        ],
      },

      // ============= MEDITATION & BREATHING =============
      { type: "header", text: "Meditation & Breathing" },

      {
        type: "exercise",
        category: "meditation",
        name: "Kapalbhati",
        image: require("../../assets/images/periods-exercise/kapalbhati.png"),
        steps: [
          "1. Sit comfortably with a straight back",
          "2. Take a deep breath in",
          "3. Forcefully exhale through your nose by pulling your belly in",
          "4. Let the inhale happen naturally",
          "5. Repeat this fast exhale-inhale cycle for about 5 minutes",
        ],
        benefits: [
          "Boosts metabolism and clears toxins from body",
          "Best in morning time on empty stomach",
        ],
        precautions: "Avoid during menstruation or if you have BP or hernia",
      },
      {
        type: "exercise",
        category: "meditation",
        name: "Bhramari",
        // image: require("../../assets/images/periods-exercise/bhramari.png"),
        steps: [
          "1. Sit comfortably with your eyes closed",
          "2. Inhale deeply through your nose",
          "3. While exhaling, make a soft humming sound like 'mmmmmm'",
          "4. Optionally, use your thumbs to gently close your ears for deeper effect",
          "5. Repeat for 20–30 seconds, 5 to 7 times",
        ],
        benefits: ["Calms nervous system", "Reduces stress and improves sleep"],
      },
      {
        type: "exercise",
        category: "meditation",
        name: "Visualization Meditation",
        // image: require("../../assets/images/periods-exercise/visualization.png"),
        steps: [
          "1. Sit comfortably in a quiet, peaceful place",
          "2. Close your eyes and take slow, deep breaths",
          "3. Imagine things that make you happy and what you love",
          "4. Stay with this positive image for 5 to 10 minutes",
        ],
        benefits: [
          "Best on empty stomach",
          "Builds self-confidence and boosts creativity and focus",
        ],
      },
    ],
    Focus: [
      "Living",
      "- Your energy starts to rise—it's time to rejoin life with creativity and motivation.",
      "- Try something new: a hobby, skill, or event.",
      "- Best time to plan dreams and create strategies.",
      "- Explore new things, say yes to new opportunities.",
      "- Your brain craves freshness—do cleaning or reset your space.",

      "Working",
      "- You’re mentally alert and energetic—perfect for work and creative thinking.",
      "- Continue deep work with boosted energy.",
      "- Communication is strong—engage in teamwork.",
      "- Great time for interviews, meetings, workshops.",
      "- Start new projects, pitch ideas, experiment freely.",
    ],
    Love: [
      "Relationships",
      "- At this phase, you are more playful , laughing , meeting new people and being more social.",
      "- Reconnect with friends, go on dates, plan group events.",
      "- This is the great time to resolve the issues as you are mentally calm and emotionally balanced.",
      "- As your self confidence rises , letting people love you recharge you emotionally.",
      "- If single, it’s a great time to meet new people or go on dates.",

      "Sex Status",
      "- Your sex drive is increasing during this phase.",
      "- your skin glows , energy returns and feel more attractive and you want to feel bolder.",
      "- Try new things in relationship , communicate with your partner.",
      "- Express yourself . Go for walk , teasing , cuddling deepens closeness with your partner.",
    ],
  },
  "Ovulatory Phase": {
    Food: [
      "Cooling & Anti-Inflammatory Foods",
      "  1. Cucumber                      2. Watermelon",
      "  3. Yogurt / Curd                4. Lemon water",
      "  5. Mint (Pudina)                6. Citrus fruit (Oranges)",
      "  7. Amala juice                  8. Fenugreek water (Methi pani)",

      "Fertility Boosting Foods",
      "  1. Eggs                         2. Pumpkin seeds",
      "  3. Pomegranate                  4. Cauliflower / Cabbage",
      "  5. Green leafy vegetables       6. Avocado",
      "  7. Chicken                      8. Gundruk",
      "  9. Mushrooms                   10. Dal (Mung dal / Musuro dal)",

      "Higher Fiber Foods",
      "  1. Apple                        2. Pear (Nashpati)",
      "  3. Lentils (Rahar / Musuro dal) 4. Millet",
      "  5. Barley / Brown rice          6. Corn flour",

      "Tips",
      "- Stay hydrated with herbal teas (tulsi + ginger), lemon or mint water.",
      "- Avoid deep-fried and spicy foods.",
      "- Include foods like gundruk and yogurt.",
      "- Avoid sugary drinks and excess tea/coffee.",
    ],
    Exercise: [
      // ==================== YOGA POSES ====================
      { type: "header", text: "Yoga Poses" },

      {
        type: "exercise",
        category: "yoga",
        name: "Bhujangasana",
        image: require("../../assets/images/periods-exercise/bhujangasana.png"),
        steps: [
          "1. Lie down on your stomach",
          "2. Put your hands under your shoulders",
          "3. Slowly breathe in and lift your chest up",
          "4. Use your back strength, not your hands",
          "5. Look up and stay like that for 20–30 seconds",
          "6. Come down slowly",
          "7. Do this 3–4 times",
        ],
        benefits: [
          "Boosts energy and mood",
          "Open heart and improve spinal flexibility",
        ],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Dhanurasana (Bow pose)",
        image: require("../../assets/images/periods-exercise/dhanurasana.png"),
        steps: [
          "1. Lie on your stomach",
          "2. Bend your knees and hold your ankles with your hands",
          "3. Breathe in and lift your chest and legs together",
          "4. Your body will look like a bow",
          "5. Stay like that for 15–30 seconds",
          "6. Do this 2–3 times",
        ],
        benefits: [
          "Stimulates ovaries and uterus",
          "Relives mild back pain and menstrual discomfort",
        ],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Utkatasana",
        image: require("../../assets/images/periods-exercise/utkatasana.png"),
        steps: [
          "1. Stand straight with your feet a little apart",
          "2. Raise both hands straight up",
          "3. Now bend your knees like you are sitting on a chair",
          "4. Keep your back straight",
          "5. Stay like that for 30–40 seconds",
          "6. Do this 3 times",
        ],
        benefits: [
          "Provide strength to thighs, hips and spine",
          "Boost energy and stamina",
        ],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "Plank Pose",
        image: require("../../assets/images/periods-exercise/plank-pose.png"),
        steps: [
          "1. Lie on your stomach and then lift your body on your hands and toes",
          "2. Keep your body straight like a line",
          "3. Look down, tighten your stomach",
          "4. Stay like that for 30–60 seconds",
          "5. Do this 2 times",
        ],
        benefits: [
          "provide strength to arms, shoulders and legs",
          "Improves posture and boost body",
        ],
      },

      // ============= MEDITATION & BREATHING =============
      { type: "header", text: "Meditation & Breathing" },

      {
        type: "exercise",
        category: "meditation",
        name: "Bhramari",
        image: require("../../assets/images/periods-exercise/bhramari.png"),
        steps: [
          "1. Sit in a quiet place, cross your legs and keep your back straight",
          "2. Close your eyes and relax",
          "3. Take a deep breath in through your nose",
          "4. While breathing out, make a soft humming sound like 'mmmmmm...' (like a bee)",
          "5. You can also gently close your ears with your thumbs and rest fingers on your forehead for deeper focus",
          "6. Feel the vibration in your head and chest",
          "7. Do this for 20–30 seconds",
          "8. Repeat 5–7 times",
        ],
        benefits: ["Calms nervous system", "Reduces stress and improves sleep"],
      },
      {
        type: "exercise",
        category: "meditation",
        name: "Chandra Bhedana",
        // image: require("../../assets/images/exercise/chandra-bhedana.png"),
        steps: [
          "1. Sit comfortably with your back straight",
          "2. Use your right hand to close your right nostril with your thumb",
          "3. Slowly breathe in through your left nostril",
          "4. Hold the breath for a few seconds (as per your comfort)",
          "5. Now, close the left nostril with your ring finger and breathe out through the right nostril",
          "6. Repeat: Inhale again through the left nostril, exhale through the right nostril",
          "7. Continue this for about 3–5 minutes",
        ],
        benefits: [
          "Balance high hormonal energy during ovulation",
          "Cools down the body",
        ],
      },

      // ============== OTHER EXERCISES ==============
      { type: "header", text: "Other Exercises" },
      {
        type: "text",
        content: "- Running, Swimming, Cycling for 20-40 minutes",
      },
      {
        type: "text",
        content:
          "- You can go for intense exercise like jumping, squats, climbing",
      },
      {
        type: "text",
        content: "- You can go for group classes like Dance and Zumba",
      },
    ],
    Focus: [
      "Living",
      "- This is the time when you are glowing, sociable and very confident.",
      "- Go out, host events, meet new people.",
      "- Try new things: dancing , hosting , speaking and expanding network.",
      "- Dress up in ways where you boost your self image.",
      "- Your skin glows up and posture improve.",

      "Working",
      "- You are at your peak mental sharpness and social fluency.",
      "- Ideal time for leadership, public speaking, and collaboration.",
      "- Great time for critical work and showing you real ability.",
      "- Best phase for brainstorming ideas and initiating projects.",
      "- In this phase your brain wants interaction rather than silent focus.",
      "- This is your superwoman work phase",
      "Tips: Avoid solo deep work like heavy research now.",
    ],
    Love: [
      "Relationships",
      "- In this phase , hormones increase confidence, affection and emotional openness.",
      "- Go out talk to people , organize gatherings.",
      "- Its great time to resolve past issues calmly with partner , friends, family.",
      "- In this phase you are more open and flirty so you can express feelings or take the lead in romance.",
      "- Perfect time for dating, meetups and explore new social circles.",

      "Sex Status",
      "- Hormones works together in this phase increasing the sex drive.",
      "- You can plan a romantic evening or weekend.",
      "- Show slow and emotional affection towards the partner.",
      "- Its great time to have open communication like sharing your preferences with your partner.",
      "- This is the phase to explore the pleasure for yourself.",
    ],
  },
  "Luteal Phase": {
    Food: [
      "Warming & Comforting Foods",
      "- Relax the nervous system, improve digestion and make you calm.",
      "  1. Warm Soups (Dal soup, Bone soup)     2. Sweet Potato",
      "  3. Turmeric milk                       4. Banana",
      "  5. Ginger tea                          6. Brown rice",
      "  7. Vegetables with ghee (carrots, beans)  8. Cumin water (Jeera pani)",

      "Hormone Supporting Foods",
      "- Help produce progesterone, balance mood swings and energy.",
      "  1. Eggs                                2. Fatty Fish",
      "  3. Chicken                             4. Avocado",
      "  5. Sesame seeds (Til)                 6. Paneer",
      "  7. Millet (Kodo)                      8. Barley (Jau)",
      "  9. Almonds and Walnuts",

      "Cramp & Bloating Relief Foods",
      "- Helps to reduce cramps, bloating and indigestion.",
      "  1. Papaya                              2. Yogurt",
      "  3. Cucumber                            4. Pineapple",
      "  5. Beetroot (Chukandar)               6. Warm lemon water",
      "  7. Coriander seed water (Dhaniya pani) 8. Spinach / Green leafy vegetables",

      "Tips",
      "- Reduce excess salt and sugar.",
      "- Limit caffeine and alcohol.",
      "- Stay hydrated.",
      "- Avoid cold foods and drinks.",
    ],
    Exercise: [
      // ==================== YOGA POSES ====================
      { type: "header", text: "Yoga Poses" },

      {
        type: "exercise",
        category: "yoga",
        name: "1. Apanasana",
        image: require("../../assets/images/periods-exercise/apanasana.png"),
        steps: [
          "1. Lie on your back with legs straight.",
          "2. Slowly bend both knees and bring them close to your chest.",
          "3. Wrap your arms around your knees.",
          "4. Keep your head on the floor and breathe deeply.",
          "5. Stay in this pose for **2–3 minutes** with slow breathing",
        ],
        benefits: [
          "Relief to lower back and intestine",
          "Relieves gas and bloating",
        ],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "2. Ananda Balasana",
        image: require("../../assets/images/periods-exercise/ananda-balasana.png"),
        steps: [
          "1. Lie on your back.",
          "2. Bend your knees and bring them towards your chest.",
          "3. Hold the outsides of your feet with your hands.",
          "4. Gently pull your knees down toward your armpits.",
          "5. Keep your back flat on the ground and breathe slowly.",
          "6. Stay in the pose for **2–3 minutes**.",
        ],
        benefits: [
          "Reduces cramps and tension and open hips",
          "Calms nervous system and improve mood",
        ],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "3. Parivrtta Janu Sirsasana",
        image: require("../../assets/images/periods-exercise/parivrtta-janu.png"),
        steps: [
          "1. Sit on the floor with one leg stretched out and the other leg bent inward.",
          "2. Turn your body slightly toward the stretched leg.",
          "3. Raise the same side arm and bend sideways toward the foot.",
          "4. Reach the foot or ankle gently (don't force).",
          "5. The other arm can rest on your bent knee or behind your back.",
          "6. Breathe and hold for **30 seconds**, then switch sides.",
          "7. **Repeat 2 times each side**.",
        ],
        benefits: [
          "Supports digestion and maintain liver",
          "Body stretches and calms mind",
        ],
        tips: ["Avoid forcing and don't do if you are too tired or crampy"],
      },
      {
        type: "exercise",
        category: "yoga",
        name: "4. Supta Matsyendrasana",
        // image: require("../../assets/images/periods-exercise/supta_matsyendrasana.png"),
        steps: [
          "1. Lie on your back.",
          "2. Bend your right knee and bring it across your body to the left side.",
          "3. Keep your shoulders flat on the ground.",
          "4. Stretch your right arm to the side and look right.",
          "5. Relax and breathe deeply.",
          "6. Hold for **1–2 minutes**, then switch sides.",
          "7. **Repeat 2 times each side**.",
        ],
        benefits: [
          "Eases digestion and bloating",
          "Releases tension from spine and abdomen area",
        ],
      },

      // ============= MEDITATION & BREATHING =============
      { type: "header", text: "Meditation & Breathing" },

      {
        type: "exercise",
        category: "meditation",
        name: "1. Nadi Shodhana",
        // image: require("../../assets/images/periods-exercise/nadi_shodhana.png"),
        steps: [
          "1. Sit comfortably with your back straight.",
          "2. Use your **right thumb** to close your **right nostril**.",
          "3. Slowly **inhale through your left nostril**.",
          "4. Now, **close the left nostril** using your ring finger.",
          "5. **Exhale through the right nostril**.",
          "6. Then **inhale through the right nostril**,",
          "7. **Close the right**, and **exhale through the left nostril**.",
          "8. This is one round, Repeat this for **3–5 minutes** with calm breathing.",
        ],
        benefits: [
          "Calms anxiety, restlessness and provide emotional support",
          "Hormonal balance by calming nervous system",
        ],
      },
      {
        type: "exercise",
        category: "meditation",
        name: "2. Yoga Nidra",
        image: require("../../assets/images/periods-exercise/yoga-nidra.png"),
        steps: [
          "1. Lie flat on your back, arms and legs relaxed.",
          "2. Close your eyes and take a few deep breaths.",
          "3. Let your whole body feel heavy and calm.",
          "4. Imagine something peaceful – like clouds, ocean, or someone you love.",
          "5. Feel relaxed from head to toe.",
          "6. Stay in this restful state for **10–20 minutes**, especially before bed or after a tiring day.",
        ],
        benefits: [
          "Provide deep mental and physical rest",
          "Reduces premenstrual syndrome(PMS) including mood swings, depression, cravings and tender breasts.",
        ],
      },
      {
        type: "exercise",
        category: "meditation",
        name: "3. Bhramari",
        image: require("../../assets/images/periods-exercise/bhramari.png"),
        steps: [
          "1. Sit quietly with your eyes closed.",
          "2. Place your thumbs gently on your ears (to close them softly).",
          "3. Take a deep breath through your nose.",
          "4. While exhaling, make a soft humming sound like 'mmmmmm...'",
          "5. Feel the vibration in your head.",
          "6. Do this for **20–30 seconds**, and repeat **5–7 times**.",
        ],
        benefits: ["Calms nervous system", "Reduces stress and improves sleep"],
      },

      // ============== TIPS ==============
      { type: "header", text: "Tips" },
      {
        type: "text",
        content: "Don't go for high strength training",
      },
      {
        type: "text",
        content: "Go for normal walk for 20-30 minutes, try nature or parks",
      },
      {
        type: "text",
        content: "Can do dance also",
      },
      {
        type: "text",
        content: "Avoid competitive sports",
      },
    ],
    Focus: [
      "Living",
      "- You may feel more emotional and sensitive , that’s normal.",
      "- Don't force yourself to socialize.",
      "- Surround yourself with calming things: soft lighting , clean spaces , herbal teas etc.",
      "- If you need time alone let the close ones know.",
      "- Choose peace over pleasure.",
      "- Try to take break from social media before an hour before bed time.",

      "Working",
      "- Don’t go for highly stressing works .",
      "- Not ideal time for public speaking or networking.",
      "- Avoid roles that demands intense energy like leadership roles.",
      "- Go for quiet space and creative works.",
      "- You can have good productivity but slow pace.",
      "- Take more breaks than usual , if you feel emotionally more reactive.",

      "Tip",
      "- Don’t force yourself into high output.",
    ],
    Love: [
      "Relationships",
      "- You feel more easily hurt and emotional. Small issues might feel big, give yourself space",
      "- Don’t force yourself into conversations or social plans, its okay to say no",
      "- Try to stay away from arguments, cause in this phase arguments can lead worse",
      "- Its common to overthink in this phase, instead of overthinking do simple things like watch movie , spend time with someone calm",

      "Sex Status",
      "- You may not fell sexy cause your body wants comfort than pressure",
      "- Focus on cuddling, massage or lying close together",
      "- Go for slow and emotional intimacy, if you are in good mood",
      "- Don’t be afraid to say what you want clearly to your partner",
      "- If you are single, give time to yourself",

      "Tips:",
      "- Avoid unnecessary conflicts",
      "- Focus on self- love",
      "- Prioritize yourself before anything",
    ],
  },
};
